#!/bin/sh

# parser: VOL

# source config
. $(dirname $1)/config

  snd_line=`amixer get Master | grep ': Playback' | tail -n 1`

[[ ! -z `echo $snd_line | grep -o "\[off\]"` ]] && snd_sym=M || snd_sym=+

echo $snd_line | sed -un 's/.*\[\([0-9]*\)%\].*/\1/p' | (read lvl; printf "VOL$snd_sym $lvl\n") > "${panel_fifo}" &

